### ISSUE TITLE
.zshrc:180: parse error near `\n'

### ISSUE THREAD

**Issue by jacklanda** [docksal/get.docksal.io#4]
![图片](https://user-images.githubusercontent.com/54089835/85872480-64465e00-b802-11ea-91bb-00866b543241.png)

![图片](https://user-images.githubusercontent.com/54089835/85872778-cacb7c00-b802-11ea-8689-f52725f4b4a2.png)

it always shows that .zshrc:180: parse error near `\n', where should i add/delete in my .zshrc file?

**Comment by lmakarov** [comment]
Sorry, but this does not seem to be related to Docksal/Docksal installer (get.docksal.io).
