### ISSUE TITLE
zsh: parse error near `\n'

### ISSUE THREAD

**Issue by YCMAT** [docksal/get.docksal.io#7]
Hello guys. I just want to make you aware I don't know how to script but I try wrap app so it works with Microsoft Intune app protection policies . This error keeps popping app when I insert this. 

./IntuneMAMPackager/Contents/MacOS/IntuneMAMPackager -i /</Users/andrewlaing/Desktop/MobileCRM>/<MobileCRM_14.3.2.0_Enterprise.ipa> -o/</Users/andrewlaing/Desktop/Wrappedappfolder>/<MobileCRM_14.3.2.0_Enterprise.wrapped.ipa> -p /</Users/andrewlaing/Desktop/CERTIFICATE MATEUSZ TEST> -c <98 9F 88 89 B9 E6 C6 C8 2F 0A DB C2 CA 7D 37 74 2B B7 E3 17>

Any help will be very much appreciated. 

Thank you

**Comment by lmakarov** [comment]
Seems like you posted in the wrong repo as I cannot see any relation between your issue and Docksal/get.docksal.io
